### ISSUE TITLE
Accessing mouse coordinates using mpl_connect to add addional plots based on where the click was

### ISSUE THREAD

**Issue by prodat1** [mp-007/kivy_matplotlib_widget#20]
I am using the graph_widget.py in my project. The MatplotFigure is integrated in a KV-String

```
 BoxLayout:
            orientation: 'vertical'
            height: self.minimum_height 
            MatplotFigureCustom:
                id:myPlot
```
`self.ids["myPlot"].figcanvas.mpl_connect('motion_notify_event', on_motion)`

The event is never called. Is there another way of accessing the events, is this a bug or am I missing something?
